name: Bug Report
description: File a bug report here
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues, it is original
        required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: Tell us what bug you encountered and what should have happened
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: Please write the steps in a list form, please add code snippets
    validations:
      required: true
  - type: input
    id: versions
    attributes:
      label: Versions
      description: Please add the versions you are using
      placeholder: 0.0.0
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional context, configuration or data that might be necessary to reproduce the issue.
  - type: checkboxes
    id: terms
    attributes:
      label: Terms and Conditions
      description: By submitting this issue, I confirm that I have read and agree to the terms in the [Code of Conduct](./CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
