name: Feature request
description: Suggest an idea for this project
title: "feat: "
labels: [feat]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    id: new-feature
    attributes:
      label: Is there an existing planned feature for this?
      description: Please search to see if an issue or project item already exists for the feature you encountered.
      options:
      - label: I have searched the existing issues, it is original
        required: true
  - type: dropdown
    attributes:
      multiple: false
      label: Type of feature
      description: Select the type of feature request, the tag should also be the PR prefix.
      options:
        - "`fix` - small bug fix"
        - "`docs` - docs changes"
        - "`feat` - a new feature"
        - "`chore` - changes that do not relate to a fix or feature and don't modify src or test files (e.g. dependencies)"
        - "`refactor` - code refactor that neither fixes a bug nor adds a feature"
        - "`style` - changes that do not affect the meaning of the code"
        - "`perf` - changes that improve performance"
        - "`test` - including new or correcting previous tests"
        - "`ci` - continuous integration related"
        - "`revert` - revert commits and PR"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current behavior
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested solution
      description: Describe the solution you'd like.
  - type: input
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem or helpful links here.
  - type: checkboxes
    id: terms
    attributes:
      label: Terms and Conditions
      description: By submitting this issue, I confirm that I have read and agree to the terms in the [Code of Conduct](./CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct.
          required: true
