name: "Update Changelog and Version"

on:
  workflow_call:
    inputs:
      release_tag:
        required: true
        type: string
      release_target:
        required: true
        type: string
      release_body:
        required: true
        type: string
      release_url:
        required: true
        type: string


jobs:
  update_changelog_version:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.release_target }}

      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          latest-version: ${{ inputs.release_tag }}
          release-notes: ${{ inputs.release_body }}
          heading-text: '[${{ inputs.release_tag }}](${{ inputs.release_url }})'

      - name: Update Version
        run: |
          echo -n "${{ inputs.release_tag }}" > VERSION

      - name: Commit updated CHANGELOG and VERSION files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ inputs.release_target }}
          commit_message: 'chore(auto): update CHANGELOG and VERSION files'
          file_pattern: 'CHANGELOG.md VERSION'
          push_options: '--force'
          tagging_message: ${{ inputs.release_tag }}

      - name: Move git tag to latest commit and push it
        run: |
          git tag --force ${{ inputs.release_tag }}
          git push origin ${{ inputs.release_tag }} --force
